### ISSUE TITLE
Embed the generated code into an existing SVG

### ISSUE THREAD

**Issue by qippur** [bindreams/zint-bindings#2]
Good day,

we would like to embed the generated code into an existing SVG.
We currently treat the existing SVG as an XML object via python lxml.
Is it possible to have the SVG representation of the generated code as a python lxml object or as a string?

Thanks in advance

**Comment by bindreams** [comment]
At the moment the only way of exporting SVG that the upstream C-based project provides is writing into a file. This means that I can't really export SVG into memory (a string or an lxml object or anything else) without interacting with the filesystem, which is not really desirable IMO.

But you can write to a temporary file with an `.svg` suffix, and then read lxml from it yourself. Here's an example:
```python
from tempfile import NamedTemporaryFile

from lxml import etree
from zint import Symbol, Symbology

with NamedTemporaryFile(suffix=".svg", delete_on_close=False) as fd1:
    path = fd1.name
    # fd1.close()  # May or may not be necessary, worked for me without

    x = Symbol()
    x.symbology = Symbology.QRCODE
    x.encode("hello world")
    x.outfile = path
    x.print()

    tree = etree.parse(path)
    print(etree.tostring(tree, pretty_print=True))

```

P.S. I happen to know that zint upstream has added a `memfile()` function which would output into a memory buffer, just like what you need. But a stable version with this feature has not been released yet.

**Comment by qippur** [comment]
Thank you Anna!

It worked like a charm.
Can't wait to test the memfile capability when it will be available.

About the script: "with" keyword automatically closes the file when the program runs outside its scope.
