### ISSUE TITLE
Remove text below barcodes

### ISSUE THREAD

**Issue by qippur** [bindreams/zint-bindings#5]
Good day,

I am not an expert in the Zint API, so if this is a dumb question, please forgive me.
I would like to hide the text below a barcode. 
The API seems to indicate that setting the "text" option to an empty string will do the trick.
I tried:

```
x = Symbol()
x.symbology = Symbology.CODE128
x.text = ''
```

but I got an error:

`Property of "Symbol" object has no setter`

Did I follow the wrong path?

Thanks in advance.

**Comment by bindreams** [comment]
Hi! Very sorry for such a long response time on such a simple issue.

The option you are looking for is called `Symbol.show_hrt` (short for Human Readable Text). Set it to `False` to disable HRT generation.

I inherited the naming from the upstream project but I will add an alias property called `Symbol.show_text` to make it clearer, as well as an example in documentation.

This is by no means an excuse to not have proper documentation, but you can also search for relevant methods by calling `help(Symbol)` from an interactive python terminal, or even by directly searching in the [stub file](https://github.com/bindreams/zint-bindings/blob/main/src/zint-stubs/__init__.pyi).

**Comment by qippur** [comment]
Hi Anna.

No need to be sorry! Thank you so much for your reply. You are always very
helpful.

roberto


Il giorno gio 21 nov 2024 alle ore 17:55 Anna Zhukova <
***@***.***> ha scritto:
